### ISSUE TITLE
"Offline" label even when online on production build

### ISSUE THREAD

**Issue by zarcode** [nanohop/todo-pwa#3]
It's easy to replicate, just run production build of the app, you will see "Offline" label showing.

**Comment by chrisachard** [comment]
@zarcode Hm - I just freshly downloaded the zip from: https://github.com/nanohop/todo-pwa/tree/offline-status-indicator  Ran "yarn" to install the dependencies, "yarn build" to build it, then "serve -s build" to serve it - and I didn't see the offline label until I checked the offline checkbox in the chrome dev tools.

Could you include what OS and browser you're using?  (And if Chrome, could you make sure that the offline checkbox is unchecked?)  Thanks!

**Comment by zarcode** [comment]
All good, sorry. You can close issue

**Comment by chrisachard** [comment]
No problem!
